#!/usr/bin/env python3
"""Source-precedence resolver: the single place that turns the vendored
sourcing_map.csv `best_source` verdict into cog's effective served-text verdict
by applying data/source_overrides.json on top.

The precedence ladder (best first), documented in README "Source precedence":

    open_corpus   open TEI critical edition (First1K / Perseus, CC BY-SA)
    byzantium_gr  clean manual transcription of a PD edition (byzantium.gr Bonn)
    migne_cgpg    CC-BY OCR of a PD edition (calfa-co Patrologia Graeca)
    pd_edition    a PD edition we would OCR ourselves
    migne_pd      Migne PD per the Canon's MPG pointer (text not yet in hand)
    -- below: not a served route --
    duplicate, locked

The ladder is the policy guiding how verdicts are assigned; the per-work
exceptions live in source_overrides.json (generated by build_source_overrides.py)
and win over the ladder, each carrying its reason for audit. Pure stdlib, no
dependency on the inventory toolkit (reads only vendored / cog-owned files).
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OVERRIDES_PATH = REPO / "data" / "source_overrides.json"

# best -> worst. Lower index = preferred when several routes cover one work.
PRECEDENCE = [
    "open_corpus",
    "byzantium_gr",
    "migne_cgpg",
    "pd_edition",
    "migne_pd",
    "duplicate",
    "locked",
]
PRECEDENCE_RANK = {s: i for i, s in enumerate(PRECEDENCE)}

# best_source values that mean "we can publish this open text"
REACHABLE_SOURCES = {"open_corpus", "byzantium_gr", "migne_cgpg", "pd_edition", "migne_pd"}


def _key(tlg_id: str, work_id: str) -> tuple[str, str]:
    return tlg_id, str(work_id).zfill(3)


def load_overrides(path: Path = OVERRIDES_PATH) -> dict[tuple[str, str], dict]:
    """(tlg_id, work_id) -> override record, or {} if the file is absent."""
    if not path.exists():
        return {}
    doc = json.loads(path.read_text(encoding="utf-8"))
    return {_key(r["tlg_id"], r["work_id"]): r for r in doc.get("overrides", [])}


def resolve(tlg_id: str, work_id: str, default_best_source: str,
            overrides: dict) -> tuple[str, str | None]:
    """Effective (best_source, reason). reason is None when no override applied."""
    r = overrides.get(_key(tlg_id, work_id))
    if r is None:
        return default_best_source, None
    return r["source"], r.get("reason", "override")


def rank(source: str) -> int:
    """Ladder rank (lower = better); unknown sources sort last."""
    return PRECEDENCE_RANK.get(source, len(PRECEDENCE))
